version: 1

root:
    level: INFO
    handlers:
      - console
      - file
      #- graylog2

loggers:
    piped:
        level: INFO # override to affect logging for piped only
        #handlers: [console]
        #propagate: false

handlers:
  console:
    class: logging.StreamHandler
    formatter: repl_aware_default
    stream: ext://sys.stdout
    #level: DEBUG

#   graylog2:
#     class: graypy.GELFHandler
#     formatter: default
#     host: localhost
#     port: 12201
#     #level: DEBUG

  file:
    class : logging.handlers.RotatingFileHandler
    formatter: default
    filename: piped.log
    maxBytes: 1048576
    backupCount: 99

formatters:
  default:
    (): piped.log.UTCFormatter
    format: '%(asctime)s [%(levelname)-5s] [%(name)-25s] %(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%S,%03.f'
  repl_aware_default:
    (): piped.log.REPLAwareUTCFormatter
    format: '%(asctime)s [%(levelname)-5s] [%(name)-25s] %(message)s'
    datefmt: '%Y-%m-%dT%H:%M:%S,%03.f'